version: "3.8"
services:
  client:
    build: ./grillaClient/.
    ports:
      - ${CLIENT_PORT}:4173
    environment:
      - VITE_IPCONFIG=${IPCONFIG}/graphql
      - VITE_SEATS=${SEATS}
      - VITE_THRESHOLD=${THRESHOLD}
  server:
    build: ./grillaServer/.
    ports:
      - ${SERVER_PORT}:4000
    links:
      - monguito
    environment:
      - MONGODB_URI=mongodb://ezziel:fawst@monguito:27017
  monguito:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ezziel
      - MONGO_INITDB_ROOT_PASSWORD=fawst
